name: External SAST Security Scan

on:
#  push:  # Monitorea cambios en main y ejecuta en PRs 
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
  workflow_dispatch:  # Permite ejecución manual
  #schedule:
  #  - cron: '0 4 * * 1'  # Corre cada lunes a las 4 AM UTC

jobs:

  snyk:
    name: Snyk Security Scan
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Snyk
        run: npm install -g snyk

      - name: Run Snyk
        run: snyk test --json > snyk-report.json || true

      - name: Filter high and critical vulnerabilities
        run: |
          if [ -s snyk-report.json ] && jq -e '.vulnerabilities' snyk-report.json >/dev/null; then
            jq '[.vulnerabilities[] | select(.severity == "high" or .severity == "critical")]' snyk-report.json > snyk-high-critical.json
          else
            echo "[]" > snyk-high-critical.json
          fi

      - name: Upload Snyk Report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report
          path: snyk-high-critical.json
