name: External SAST con Trivy

on:
  # push:  # Monitorea cambios en main y ejecuta en PRs 
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:  # Permite ejecución manual
  #schedule:
  #  - cron: '0 4 * * 1'  # Corre cada lunes a las 4 AM UTC

jobs:
  trivy:
    name: Trivy Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (without running scripts)
        run: npm install --package-lock-only
    
      - name: Run Trivy
        uses: aquasecurity/trivy-action@0.29.0
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "json"
          output: "trivy-report.json"
          severity: "HIGH,CRITICAL"

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json