name: External SAST Security Scan

on:
  push:  # Monitorea cambios en main y ejecuta en PRs 
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Permite ejecución manual
  #schedule:
  #  - cron: '0 4 * * 1'  # Corre cada lunes a las 4 AM UTC


jobs:
  semgrep:
    name: Semgrep Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        run: semgrep scan --config=p/ci --json > semgrep-report.json || true

      - name: Filter high and critical vulnerabilities
        run: jq '[.results[] | select(.severity == "ERROR" or .severity == "WARNING")]' semgrep-report.json > semgrep-high-critical.json

      - name: Upload Semgrep Report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-high-critical.json

  snyk:
    name: Snyk Security Scan
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Snyk
        run: npm install -g snyk

      - name: Run Snyk
        run: snyk test --json > snyk-report.json || true

      - name: Filter high and critical vulnerabilities
        run: jq '[.vulnerabilities[] | select(.severity == "high" or .severity == "critical")]' snyk-report.json > snyk-high-critical.json

      - name: Upload Snyk Report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report
          path: snyk-high-critical.json

  trivy:
    name: Trivy Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get update && sudo apt-get install -y wget
          wget -qO- https://github.com/aquasecurity/trivy/releases/latest/download/trivy_$(dpkg --print-architecture).deb | sudo dpkg -i -

      - name: Run Trivy
        run: trivy fs --format json --severity HIGH,CRITICAL --output trivy-report.json .

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json
