name: External SAST con semgrep

on:
  push:  # Monitorea cambios en main y ejecuta en PRs 
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Permite ejecución manual
  #schedule:
  #  - cron: '0 4 * * 1'  # Corre cada lunes a las 4 AM UTC

jobs:
  semgrep:
    name: Semgrep Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        #run: semgrep scan --config=p/ci --json > semgrep-report.json || true # solo escanea CI/CD y || true evita que devuelva error parando el pipeline, sólo cuando quiero informar resultado
                                                                              # sin detener el pipeline
        #run: semgrep scan --config=p/ci --config=auto --error --json > semgrep-report.json # --config=auto detección de los lenguajes del proyecto y escaneo según eso, json exporta a json
        #run: semgrep scan --config=p/ci --config=auto --error --json | jq '[.results[] | select(.extra.metadata.impact == "MEDIUM" or .extra.metadata.impact == "HIGH")]' > semgrep-report.json # solo hallazgos de impacto high o medium
        run: semgrep scan --config=p/ci --config=auto --error --json | jq '[.results[] | select(.extra.metadata.impact == "HIGH")]' > semgrep-report.json



      - name: Upload Semgrep Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: semgrep-report
          path: semgrep-report.json
