# Este workflow ejecuta análisis de seguridad con herramientas externas como Semgrep, Snyk y Trivy, cada una en su propio job.
# p4v0nIA
name: External SAST Security Scan

on:
  workflow_dispatch:  # Se ejecuta manualmente
  #schedule:
  #  - cron: '0 4 * * 1'  # Corre cada lunes a las 4 AM UTC

jobs:
  semgrep:
    name: Semgrep Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: 'p/ci'

  snyk:
    name: Snyk Security Scan
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}  # Se necesita una API Key de Snyk
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Snyk
        uses: snyk/actions/node@master
        with:
          args: --severity-threshold=high --fail-on=all

  trivy:
    name: Trivy Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
